### PR TITLE
Makefile.am: use $(NM) as supplied by configure

### PR DESCRIPTION
**Pull request by wdlkmpx**
https://savannah.gnu.org/patch/?8657

### CODE REVIEW

**Review by rocky — COMMENTED** [review]
I'm not seeing NM as being set mentioned in [autoconf.info](https://www.gnu.org/software/autoconf/manual/autoconf-2.63/autoconf.html)

Probably safe though if 

```
NM  ?= nm
```

Is added to the top though

**Comment by wdlkmpx** [comment]
configure does check for nm
```
checking for BSD- or MS-compatible name lister (nm)... /mnt/sda3/builds_static/cross-compiler/i686-linux-musl-cross/bin/i686-linux-musl-nm -B
checking the name lister (/mnt/sda3/builds_static/cross-compiler/i686-linux-musl-cross/bin/i686-linux-musl-nm -B) interface... BSD nm
```

Makefile:
`NM = /mnt/sda3/builds_static/cross-compiler/i686-linux-musl-cross/bin/i686-linux-musl-nm -B`

```
# autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
```
autoconf is old enough, hard to tell if this works with older autoconf releases ...

**Comment by rocky** [comment]
> configure does check for nm
> 
> ```
> checking for BSD- or MS-compatible name lister (nm)... /mnt/sda3/builds_static/cross-compiler/i686-linux-musl-cross/bin/i686-linux-musl-nm -B
> checking the name lister (/mnt/sda3/builds_static/cross-compiler/i686-linux-musl-cross/bin/i686-linux-musl-nm -B) interface... BSD nm
> ```
> 
> Makefile: `NM = /mnt/sda3/builds_static/cross-compiler/i686-linux-musl-cross/bin/i686-linux-musl-nm -B`
> 
> ```
> # autoconf --version
> autoconf (GNU Autoconf) 2.69
> Copyright (C) 2012 Free Software Foundation, Inc.
> ```
> 
> autoconf is old enough, hard to tell if this works with older autoconf releases ...

Where is this behavior documented that we can rely on it? 

Setting the variable if it hasn't been set previously is the safe and reliable thing to do.

**Comment by wdlkmpx** [comment]
I think that check is triggered by AM_PROG_NM, which is not .. documented?

It's not listed in configure.ac, but it somehow autoconf determines that $(NM) must be set, as a dependency of some other macro or it probably scans the Makefile.am files or something

That check is present in vcdimager-2.0.1/configure
```
{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for BSD- or MS-compatible name lister (nm)" >&5
$as_echo_n "checking for BSD- or MS-compatible name lister (nm)... " >&6; }
```
I'm no sure how to proceed, I have no problem with keeping this open for a while

**Comment by rocky** [comment]
> I think that check is triggered by AM_PROG_NM, which is not .. documented?
> 
> It's not listed in configure.ac, but it somehow autoconf determines that $(NM) must be set, as a dependency of some other macro or it probably scans the Makefile.am files or something
> 
> That check is present in vcdimager-2.0.1/configure
> 
> ```
> { $as_echo "$as_me:${as_lineno-$LINENO}: checking for BSD- or MS-compatible name lister (nm)" >&5
> $as_echo_n "checking for BSD- or MS-compatible name lister (nm)... " >&6; }
> ```
> 
> I'm no sure how to proceed, I have no problem with keeping this open for a while

The way to proceed is to add the single line I suggested initially. 

I have no problem keeping this open for a while as well.

**Comment by wdlkmpx** [comment]
I added AM_PROG_NM to configure.ac
That macro is as old as vcdimager, part of libtool.m4
https://opensource.apple.com/source/glibtool/glibtool-3.1/libtool/configure.in.auto.html

libtool is a hard dependency: AM_PROG_LIBTOOL, but that is deprecated, LT_INIT is the new name

**Pull request closed without merging**
